# Generated by Django 4.2.3 on 2023-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Royxat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_I_SH', models.CharField(max_length=500)),
                ('Tel_raqam', models.IntegerField()),
            ],
        ),
    ]
