# Generated by Django 4.2.3 on 2023-09-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='royxat',
            old_name='F_I_SH',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='royxat',
            old_name='Tel_raqam',
            new_name='tel_raqam',
        ),
    ]
