# Generated by Django 4.2.3 on 2023-09-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_yangiliklar_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SONGI_YILLARDA_BAJARILGAN_ISHLAR_XAJMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='rasmlar/images')),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
    ]
