# Generated by Django 4.2.3 on 2023-09-14 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_songi_yillarda_bajarilgan_ishlar_xajmi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'ordering': ['-chopetilishVaqti']},
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='chopetilishVaqti',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
