# Generated by Django 4.2.3 on 2023-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_yangiliklar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuterManzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('manzil', models.TextField()),
                ('tel_raqam1', models.IntegerField()),
                ('tel_raqam2', models.IntegerField()),
            ],
        ),
    ]
